const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
const numbers = [1, 2, 3, 4, 5];  
const doubled = numbers.map(num => num * 2);  
const sum = doubled.reduce((acc, val) => acc + val, 0);  
console.log("Doubled numbers:", doubled);  
console.log("Sum of doubled numbers:", sum);  
const filtered = numbers.filter(num => num > 2);  
console.log("Filtered numbers:", filtered);  
const square = num => num * num;  
const squaredNumbers = numbers.map(square);  
console.log("Squared numbers:", squaredNumbers);
